### ISSUE TITLE
a migration only supports a single command

### ISSUE THREAD

**Issue by octplane** [Bogdanp/racket-north#2]
While trying to create a role, assign its permissions and set its password in the same migration, the postgres driver response was:

```
cannot insert multiple commands into a prepared statement
```

Because `query-exec` is meant to be used command by command.
A workaround is to create several migration, but it would probably be nice if north was handling that split internally for the user.

**Comment by Bogdanp** [comment]
Yes, this is a bit unfortunate and I've run into this problem myself. For now, I've been splitting my migrations by command. I've read the connection code for db-lib and I don't think there's an easy workaround for this and I'd rather avoid trying to parse the statements to separate them out individually since that may be error prone.  One thing we could do instead is to support multiple `@up` and `@down` blocks. For example:

```sql
#lang north

-- @revision: 9bfd76d90c767269b167d5d486665c60
-- @description: Creates the price domain and the orders table.
-- @up {
create domain price integer check(value > 0);
-- }

-- @up {
create table orders(
  id serial primary key,
  email text not null,
  created_at timestamptz not null default current_timestamp
);
-- }

-- @up {
create table order_items(
  id serial primary key,
  order_id integer not null references orders(id),
  sku text not null,
  price price not null,
  quantity integer not null check(value > 0)
);
-- }

-- @down {
drop table order_items;
-- }

-- @down {
drop table orders;
-- }

-- @down {
drop domain price;
-- }
```

What do you think about that?

**Comment by eestrada** [comment]
Using multiple `up` clauses within the same script, although not ideal, seems far less tedious than needing to create a migration per statement.

However, the bigger potential benefit is having all `up` clauses within a single migration run within the same transaction (thus allowing rollback of everything on failure of any individual statement in the migration). Some migrations are an all-or-nothing affair, so grouping all relevant statements under a single transaction is a big deal.
